### ISSUE TITLE
Não consegui fazer o teste durante a aula.

### ISSUE THREAD

**Issue by EvellynRafael** [guilhermej/dnsbrute#1]
Olá, estou fazendo seu curso de introdução a hacking e durante o uso do programa, ele está aparecendo um erro dizendo: ImportError: No module named dns.resolver.

Como eu poderia resolver?

**Comment by guilhermej** [comment]
Dúvidas em relação ao exercício somente pelo fórum de dúvidas da plataforma.

**Comment by EvellynRafael** [comment]
Oi! Eu acabei mexendo no git e tentei tirar a dúvida lá depois de ter
encontrado o fórum no site. Peço desculpas!
